# recipe/xgboost_x_learner.yaml: XGBoost X-Learner 모델 전용 설정

# 모델의 고유 이름 (파일 이름과 일치해야 함)
name: "xgboost_x_learner"

# 이 모델이 사용할 피처 증강기 레시피의 이름
augmenter: "user_summary_features"

# 데이터 입출력 명세
data_interface:
  # 모델이 사용할 피처 목록
  features:
    - "member_gender"
    - "member_age"
    - "rsvn_30_count"
    - "rsvn_90_avg_price"
    - "last_rsvn_date_elapsed"
  
  # 결과(Y) 컬럼
  target_col: "outcome"
  
  # 처치(Treatment) 컬럼
  treatment_col: "grp"
  
  # 처치 그룹을 나타내는 값
  treatment_value: "treatment"

# 모델 하이퍼파라미터
# CausalML의 XGBTRegressor에 전달될 파라미터들
hyperparameters:
  n_estimators: 200
  max_depth: 4
  learning_rate: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  min_child_weight: 1
  gamma: 0.1
  random_state: 42
  objective: "binary:logistic"
  eval_metric: "logloss"
