version: '3.8'

# NOTE: MLflow 서버가 제거되었습니다.
# modern-ml-pipeline은 이제 순수 라이브러리로서 외부 MLflow 서버에 연결하거나
# 로컬 파일 모드로 동작합니다. 
# 
# MLflow 서버가 필요한 경우 mmp-local-dev 프로젝트를 사용하시기 바랍니다.
# 
# 이 파일은 향후 modern-ml-pipeline의 개발/테스트를 위한 보조 서비스
# (예: PostgreSQL, Redis)만 제공합니다.

services:
  postgres-mmp-dev:
    image: postgres:13
    container_name: postgres-mmp-dev
    restart: always
    ports:
      - "5433:5432" # 포트 충돌 방지를 위해 5433으로 변경
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlflow

  redis-mmp-dev:
    image: redis:6
    container_name: redis-mmp-dev
    restart: always
    ports:
      - "6380:6379" # 포트 충돌 방지를 위해 6380으로 변경

volumes:
  postgres_data:
