artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/6c22822e2b724736b0b7bb6ffffd0c80/artifacts
end_time: 1753609466925
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: 6c22822e2b724736b0b7bb6ffffd0c80
run_name: LogisticRegression_final_classification_test_20250727_184426
source_name: ''
source_type: 4
source_version: ''
start_time: 1753609466825
status: 4
tags: []
user_id: wooshikwon
