class_path: "xgboost.XGBClassifier"
description: "XGBoost Classifier."
library: "xgboost"
hyperparameters:
  # 고정 파라미터 (모든 환경 동일)
  fixed:
    random_state: 42
    tree_method: "hist"
    eval_metric: "logloss"
  # Optuna 최적화 대상 파라미터 (범위 지정)
  tunable:
    n_estimators:
      type: "int"
      range: [50, 1000]
      default: 100
    max_depth:
      type: "int"
      range: [3, 10]
      default: 6
    learning_rate:
      type: "float"
      range: [0.01, 0.3]
      default: 0.1
    subsample:
      type: "float"
      range: [0.5, 1.0]
      default: 1.0
    colsample_bytree:
      type: "float"
      range: [0.5, 1.0]
      default: 1.0
    colsample_bylevel:
      type: "float"
      range: [0.5, 1.0]
      default: 1.0
    colsample_bynode:
      type: "float"
      range: [0.5, 1.0]
      default: 1.0
    reg_alpha:
      type: "float"
      range: [0.0, 10.0]
      default: 0.0
    reg_lambda:
      type: "float"
      range: [0.1, 10.0]
      default: 1.0
    gamma:
      type: "float"
      range: [0.0, 5.0]
      default: 0.0
    min_child_weight:
      type: "int"
      range: [1, 10]
      default: 1
    scale_pos_weight:
      type: "float"
      range: [0.1, 10.0]
      default: 1.0
  # 환경별 기본값
  environment_defaults:
    local:
      n_estimators: 50
      max_depth: 3
      learning_rate: 0.1
      subsample: 0.8
    dev:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      subsample: 0.9
    prod:
      n_estimators: 200
      max_depth: 6
      learning_rate: 0.05
      subsample: 0.9
# 지원 태스크 및 요구사항
supported_tasks: ["binary_classification", "multiclass_classification"]
feature_requirements:
  numerical: true
  categorical: true
  text: false