artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/c38bde34af2945ad906a5df88269aae0/artifacts
end_time: 1753601857900
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: c38bde34af2945ad906a5df88269aae0
run_name: RandomForestClassifier_e2e_classification_test_20250727_163737
source_name: ''
source_type: 4
source_version: ''
start_time: 1753601857443
status: 4
tags: []
user_id: wooshikwon
