artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/44b0cb7b5c2b40cf89c772017ca9815d/artifacts
end_time: 1753609992065
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: 44b0cb7b5c2b40cf89c772017ca9815d
run_name: LogisticRegression_final_classification_test_20250727_185311
source_name: ''
source_type: 4
source_version: ''
start_time: 1753609991941
status: 4
tags: []
user_id: wooshikwon
