# CatBoost Classifier - 범주형 데이터 특화 그래디언트 부스팅
# 🐱 범주형 피처 자동 처리와 뛰어난 성능의 결합

name: "catboost_classifier"

model:
  # 직접 동적 import를 통한 CatBoost 분류기
  class_path: "catboost.CatBoostClassifier"
  
  # 하이퍼파라미터 정의 (Optuna 자동 최적화 지원)
  hyperparameters:
    # 🔥 자동 최적화 범위 - CatBoost 특화 하이퍼파라미터
    learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
    iterations: {type: "int", low: 100, high: 1000}
    depth: {type: "int", low: 4, high: 10}
    l2_leaf_reg: {type: "float", low: 1.0, high: 10.0}
    border_count: {type: "int", low: 32, high: 255}
    bagging_temperature: {type: "float", low: 0.0, high: 1.0}
    random_strength: {type: "float", low: 0.0, high: 1.0}
    
    # 🔧 고정값 - CatBoost 안정성을 위한 필수 설정
    random_state: 42
    loss_function: "Logloss"
    eval_metric: "AUC"
    verbose: false
    auto_class_weights: "Balanced"

  # 하이퍼파라미터 튜닝 설정
  hyperparameter_tuning:
    enabled: true
    n_trials: 100
    metric: "roc_auc"
    direction: "maximize"

  # 데이터 로더 정의 (Spine 생성)
  loader:
    name: "classification_loader"
    source_uri: "recipes/sql/loaders/user_features.sql"

  # 피처 증강 정의 (Feature Store 기반)
  augmenter:
    type: "feature_store"
    features:
      # 사용자 기본 정보 피처
      - feature_namespace: "user_demographics"
        features: ["age", "country_code"]
      
      # 사용자 구매 이력 피처  
      - feature_namespace: "user_purchase_summary"
        features: ["ltv", "total_purchase_count", "last_purchase_date"]
      
      # 상품 상세 정보 피처
      - feature_namespace: "product_details"
        features: ["price", "category", "brand"]
      
      # 세션 행동 피처
      - feature_namespace: "session_summary"
        features: ["time_on_page_seconds", "click_count"]

  # 전처리 설정
  preprocessor:
    name: "simple_scaler"
    params:
      criterion_col: null
      # 엔티티 키와 타임스탬프 제외
      exclude_cols: ["user_id", "product_id", "session_id", "event_timestamp"]

  # 데이터 인터페이스 정의
  data_interface:
    task_type: "classification"
    target_col: "target_class"

  # 평가자 설정
  evaluator:
    name: "classification_evaluator"

# 평가 설정
evaluation:
  metrics:
    - "accuracy"
    - "precision_weighted"
    - "recall_weighted" 
    - "f1_weighted"
    - "roc_auc"
  
  validation:
    method: "train_test_split"
    test_size: 0.2
    stratify: true
    random_state: 42

# 💡 사용 예시:
# APP_ENV=dev uv run python main.py train --recipe-file models/classification/catboost_classifier 