# LightGBM Classifier - 빠르고 효율적인 그래디언트 부스팅
# ⚡ 메모리 효율성과 빠른 학습 속도의 완벽한 조화

name: "lightgbm_classifier"

model:
  # 직접 동적 import를 통한 LightGBM 분류기
  class_path: "lightgbm.LGBMClassifier"
  
  # 하이퍼파라미터 정의 (Optuna 자동 최적화 지원)
  hyperparameters:
    # 🔥 자동 최적화 범위 - LightGBM 특화 하이퍼파라미터
    learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
    n_estimators: {type: "int", low: 100, high: 1000}
    num_leaves: {type: "int", low: 10, high: 300}
    max_depth: {type: "int", low: 3, high: 15}
    feature_fraction: {type: "float", low: 0.4, high: 1.0}
    bagging_fraction: {type: "float", low: 0.4, high: 1.0}
    bagging_freq: {type: "int", low: 1, high: 7}
    min_child_samples: {type: "int", low: 5, high: 100}
    reg_alpha: {type: "float", low: 0.0, high: 1.0}
    reg_lambda: {type: "float", low: 0.0, high: 1.0}
    
    # 🔧 고정값 - LightGBM 안정성을 위한 필수 설정
    random_state: 42
    objective: "binary"
    metric: "binary_logloss"
    verbosity: -1
    force_col_wise: true

  # 하이퍼파라미터 튜닝 설정
  hyperparameter_tuning:
    enabled: true
    n_trials: 120  # LightGBM은 빠르므로 더 많은 trial 가능
    metric: "f1_weighted"
    direction: "maximize"

  # 데이터 로더 정의 (Spine 생성)
  loader:
    name: "classification_loader"
    source_uri: "recipes/sql/loaders/user_features.sql"

  # 피처 증강 정의 (Feature Store 기반)
  augmenter:
    type: "feature_store"
    features:
      # 사용자 기본 정보 피처
      - feature_namespace: "user_demographics"
        features: ["age", "country_code"]
      
      # 사용자 구매 이력 피처  
      - feature_namespace: "user_purchase_summary"
        features: ["ltv", "total_purchase_count", "last_purchase_date"]
      
      # 상품 상세 정보 피처
      - feature_namespace: "product_details"
        features: ["price", "category", "brand"]
      
      # 세션 행동 피처
      - feature_namespace: "session_summary"
        features: ["time_on_page_seconds", "click_count"]

  # 전처리 설정
  preprocessor:
    name: "simple_scaler"
    params:
      criterion_col: null
      # 엔티티 키와 타임스탬프 제외
      exclude_cols: ["user_id", "product_id", "session_id", "event_timestamp"]

  # 데이터 인터페이스 정의
  data_interface:
    task_type: "classification"
    target_col: "target_class"

  # 평가자 설정
  evaluator:
    name: "classification_evaluator"

# 평가 설정
evaluation:
  metrics:
    - "accuracy"
    - "precision_weighted"
    - "recall_weighted" 
    - "f1_weighted"
    - "roc_auc"
  
  validation:
    method: "train_test_split"
    test_size: 0.2
    stratify: true
    random_state: 42

# 💡 사용 예시:
# APP_ENV=dev uv run python main.py train --recipe-file models/classification/lightgbm_classifier 