# LightGBM Classifier: 초고속 그래디언트 부스팅
# ⚡ 속도와 메모리 효율성의 완벽한 조화

name: "lightgbm_classifier"

model:
  # LightGBM Classifier 직접 동적 import
  class_path: "lightgbm.LGBMClassifier"
  
  # Phase 1: Point-in-Time 정합성 스키마
  loader:
    name: "customer_churn_loader"
    source_uri: "recipes/sql/loaders/customer_churn_features.sql"
    adapter: sql
    entity_schema:
      entity_columns: ["customer_id"]
      timestamp_column: "snapshot_date"
  
  # 기존: ML 작업별 세부 설정 (Classification 전용)
  data_interface:
    task_type: "classification"
    target_column: "will_churn"           # 이탈 예측 (0: 유지, 1: 이탈)
    class_weight: "balanced"              # 이탈/유지 클래스 균형
    average: "weighted"
    
  # Dictionary 형태 하이퍼파라미터 (LightGBM 특화)
  hyperparameters:
    # 부스팅 설정
    num_leaves: {type: "int", low: 20, high: 300}           # 리프 노드 수
    learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
    n_estimators: {type: "int", low: 100, high: 1000}
    
    # 트리 구조 제어
    max_depth: {type: "int", low: 3, high: 12}
    min_child_samples: {type: "int", low: 5, high: 100}
    min_child_weight: {type: "float", low: 0.001, high: 0.1, log: true}
    
    # 정규화
    reg_alpha: {type: "float", low: 0, high: 1}            # L1 정규화
    reg_lambda: {type: "float", low: 0, high: 1}           # L2 정규화
    
    # 샘플링 (LightGBM 특화)
    subsample: {type: "float", low: 0.6, high: 1.0}
    colsample_bytree: {type: "float", low: 0.6, high: 1.0}
    subsample_freq: {type: "int", low: 1, high: 5}         # 샘플링 빈도
    
    # 고정값
    random_state: 42
    n_jobs: -1
    verbosity: -1                                          # 조용한 실행
    class_weight: "balanced"

  # 하이퍼파라미터 튜닝 설정
  hyperparameter_tuning:
    enabled: true
    n_trials: 120                     # LightGBM은 빠르므로 많은 trial
    metric: "roc_auc"
    direction: "maximize"
  
  # Feature Store 기반 피처 증강
  augmenter:
    type: "feature_store"
    features:
      # 사용자 활동 패턴
      - feature_namespace: "user_activity"
        features: ["login_frequency", "session_duration", "feature_usage_count", "last_active_days"]
      
      # 구독 및 결제 패턴
      - feature_namespace: "subscription_behavior"
        features: ["subscription_duration", "payment_delays", "plan_changes", "support_tickets"]
      
      # 참여도 지표
      - feature_namespace: "engagement_metrics"
        features: ["content_consumed", "social_interactions", "feedback_scores", "recommendation_clicks"]
      
      # 고객 가치
      - feature_namespace: "customer_value"
        features: ["lifetime_value", "monthly_revenue", "referral_count", "premium_features_used"]

  # 전처리 설정
  preprocessor:
    name: "classification_preprocessor"
    params:
      criterion_col: null
      exclude_cols: ["user_id", "subscription_tier", "feature_extraction_date", "will_churn"]
      handle_missing: "median"
      scale_features: false        # LightGBM은 스케일링 불필요
      encode_categorical: "label"   # Label encoding for LightGBM

  # 평가자 설정
  evaluator:
    name: "classification_evaluator"

# 평가 설정
evaluation:
  metrics:
    - "accuracy"
    - "precision_weighted"
    - "recall_weighted"
    - "f1_weighted"
    - "roc_auc"
  
  validation:
    method: "train_test_split"
    test_size: 0.2
    stratify: true
    random_state: 42
