# XGBoost Classifier - Blueprint v17.0 Automated Excellence
# 🚀 Gradient Boosting의 혁신, 뛰어난 성능과 효율성의 결합

# 1. 모델 기본 정보 (직접 동적 import)
class_path: "xgboost.XGBClassifier"

# 2. 데이터 로더 정의
loader:
  name: "classification_dataset"
  source_uri: "bq://recipes/sql/loader/classification_features.sql"
  local_override_uri: "file://local/data/sample_classification.csv"

# 3. 피처 증강기 정의 (🆕 Blueprint v17.0 - Feature Store 방식)
augmenter:
  type: "feature_store"
  features:
    # 사용자 기본 정보
    - feature_namespace: "user_demographics"
      features: ["age", "gender", "education_level", "income_bracket"]
    # 행동 패턴 피처
    - feature_namespace: "user_behavior"
      features: ["click_through_rate", "session_frequency", "avg_session_duration"]
    # 구매 이력 피처
    - feature_namespace: "purchase_history"
      features: ["total_orders", "avg_order_value", "preferred_category"]
    # 시간 기반 피처
    - feature_namespace: "temporal_features"
      features: ["recency_score", "frequency_score", "monetary_score"]

# 4. 전처리기 정의
preprocessor:
  name: "simple_scaler"
  params:
    criterion_col: null
    exclude_cols: ["user_id", "event_timestamp"]

# 5. 모델 인터페이스
data_interface:
  task_type: "classification"
  
  features:
    age: "numeric"
    gender: "category"
    education_level: "category"
    income_bracket: "category"
    click_through_rate: "numeric"
    session_frequency: "numeric"
    avg_session_duration: "numeric"
    total_orders: "numeric"
    avg_order_value: "numeric"
    preferred_category: "category"
    recency_score: "numeric"
    frequency_score: "numeric"
    monetary_score: "numeric"
  
  target_col: "target_class"
  class_weight: "balanced"
  average: "weighted"

# 🆕 6. 하이퍼파라미터 (Dictionary 형식 + 자동 튜닝)
hyperparameters:
  # 🔥 자동 최적화 범위 (XGBoost 특화)
  learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
  n_estimators: {type: "int", low: 100, high: 1000}
  max_depth: {type: "int", low: 3, high: 10}
  subsample: {type: "float", low: 0.6, high: 1.0}
  colsample_bytree: {type: "float", low: 0.6, high: 1.0}
  min_child_weight: {type: "int", low: 1, high: 10}
  gamma: {type: "float", low: 0.0, high: 1.0}
  reg_alpha: {type: "float", low: 0.0, high: 1.0}
  reg_lambda: {type: "float", low: 0.0, high: 1.0}
  
  # 🔧 고정값
  random_state: 42
  objective: "binary:logistic"
  eval_metric: "auc"
  use_label_encoder: false

# 🆕 7. 하이퍼파라미터 튜닝 설정
hyperparameter_tuning:
  enabled: true
  n_trials: 100
  metric: "roc_auc"
  direction: "maximize" 