# config/data_adapters.yaml: 어댑터 기술 스택 정의의 유일한 출처(SSoT)
# -----------------------------------------------------------------------------
# 이 파일은 어떤 환경에서 어떤 목적(loader, storage)에 어떤 어댑터 기술을 사용할지를 정의합니다.
# `base.yaml`의 인프라 설정과 분리되어, 모델의 논리적 실행에 필요한 기술 스택을 명시합니다.
# -----------------------------------------------------------------------------

data_adapters:
  default_loader: storage
  default_storage: storage
  adapters:
    storage:
      class_name: StorageAdapter
      config: {}
    sql:
      class_name: SqlAdapter
      config:
        connection_uri: "postgresql://user:pass@localhost:5433/db"
    feature_store:
      class_name: FeastAdapter
      config: {} 