artifact_location: file:///Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/0
creation_time: 1753541131845
experiment_id: '0'
last_update_time: 1753541131845
lifecycle_stage: active
name: Default
