artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/a5bc456e159f407c95c0b2e8c6325ff3/artifacts
end_time: 1753610294429
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: a5bc456e159f407c95c0b2e8c6325ff3
run_name: LogisticRegression_final_classification_test_20250727_185814
source_name: ''
source_type: 4
source_version: ''
start_time: 1753610294339
status: 4
tags: []
user_id: wooshikwon
