artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/0d491961893047c8add93f3ceec30ae8/artifacts
end_time: 1753610207997
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: 0d491961893047c8add93f3ceec30ae8
run_name: test_run
source_name: ''
source_type: 4
source_version: ''
start_time: 1753610207989
status: 3
tags: []
user_id: wooshikwon
