artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/9ba7d0013e134ff48aea986c488a8c07/artifacts
end_time: 1753609347754
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: 9ba7d0013e134ff48aea986c488a8c07
run_name: LogisticRegression_final_classification_test_20250727_184227
source_name: ''
source_type: 4
source_version: ''
start_time: 1753609347652
status: 4
tags: []
user_id: wooshikwon
