artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/6bc7c4aaaae94139818cfa46a85cf968/artifacts
end_time: 1753609171740
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: 6bc7c4aaaae94139818cfa46a85cf968
run_name: LogisticRegression_local_classification_test_v2_20250727_183931
source_name: ''
source_type: 4
source_version: ''
start_time: 1753609171633
status: 4
tags: []
user_id: wooshikwon
