
# config/data_adapters.yaml
# 어떤 기술을 사용할지 정의합니다.
data_adapters:
  # Phase 2 통합 어댑터 사용을 기본으로 설정합니다.
  default_loader: storage
  default_storage: storage
  adapters:
    storage:
      class_name: StorageAdapter
      config: {}
    sql:
      class_name: SqlAdapter
      config:
        # 이 URI는 base.yaml이나 dev.yaml에서 덮어써야 합니다.
        connection_uri: "postgresql://user:pass@localhost:5432/db"
