artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/ccf6623abc6845a9b29cd6b7ae4f11f8/artifacts
end_time: 1753610117285
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: ccf6623abc6845a9b29cd6b7ae4f11f8
run_name: LogisticRegression_final_classification_test_20250727_185517
source_name: ''
source_type: 4
source_version: ''
start_time: 1753610117176
status: 4
tags: []
user_id: wooshikwon
