# LightGBM Regressor: 초고속 그래디언트 부스팅
# ⚡ 빠르고 효율적인 그래디언트 부스팅으로 실시간 예측

name: "lightgbm_regressor"

model:
  # LightGBM Regressor 직접 동적 import
  class_path: "lightgbm.LGBMRegressor"
  
  # Phase 1: Point-in-Time 정합성 스키마
  loader:
    name: "demand_forecasting_loader"
    source_uri: "recipes/sql/loaders/demand_prediction_features.sql"
    entity_schema:
      entity_columns: ["product_id", "region_id"]       # 제품-지역 페어
      timestamp_column: "forecast_week"                 # 예측 주차
  
  # 기존: ML 작업별 세부 설정 (Regression 전용)
  data_interface:
    task_type: "regression"
    target_column: "weekly_demand_units"       # 주간 수요량 (단위)
    
  # Dictionary 형태 하이퍼파라미터 (LightGBM 특화)
  hyperparameters:
    # 부스팅 설정
    num_leaves: {type: "int", low: 20, high: 300}
    learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
    n_estimators: {type: "int", low: 100, high: 1000}
    
    # 트리 구조 제어
    max_depth: {type: "int", low: 3, high: 12}
    min_child_samples: {type: "int", low: 5, high: 100}
    min_child_weight: {type: "float", low: 0.001, high: 0.1, log: true}
    
    # 정규화
    reg_alpha: {type: "float", low: 0, high: 1}
    reg_lambda: {type: "float", low: 0, high: 1}
    
    # 샘플링
    subsample: {type: "float", low: 0.6, high: 1.0}
    colsample_bytree: {type: "float", low: 0.6, high: 1.0}
    subsample_freq: {type: "int", low: 1, high: 5}
    
    # 고정값
    random_state: 42
    n_jobs: -1
    verbosity: -1

  # 하이퍼파라미터 튜닝 설정
  hyperparameter_tuning:
    enabled: true
    n_trials: 120                     # LightGBM은 빠르므로 많은 trial
    metric: "neg_mean_absolute_percentage_error"
    direction: "maximize"
  
  # Feature Store 기반 피처 증강
  augmenter:
    type: "feature_store"
    features:
      # 과거 수요 패턴
      - feature_namespace: "historical_demand"
        features: ["lag_1_week", "lag_2_week", "lag_4_week", "rolling_avg_4w", "trend_slope"]
      
      # 계절성 요인
      - feature_namespace: "seasonality_factors"
        features: ["week_of_year", "month", "quarter", "holiday_effect", "seasonal_index"]
      
      # 제품 특성
      - feature_namespace: "product_attributes"
        features: ["category", "price_tier", "promotion_sensitivity", "lifecycle_stage", "substitutes_count"]
      
      # 외부 요인
      - feature_namespace: "external_factors"
        features: ["economic_index", "competitor_activity", "weather_impact", "marketing_spend"]

  # 전처리 설정
  preprocessor:
    name: "regression_preprocessor"
    params:
      criterion_col: null
      exclude_cols: ["product_id", "region_id", "forecast_week", "weekly_demand_units"]
      handle_missing: "median"
      scale_features: false        # LightGBM은 스케일링 불필요
      encode_categorical: "label"

  # 평가자 설정
  evaluator:
    name: "regression_evaluator"

# 평가 설정
evaluation:
  metrics:
    - "r2_score"
    - "mean_absolute_error"
    - "mean_squared_error"
    - "root_mean_squared_error"
  
  validation:
    method: "train_test_split"
    test_size: 0.2
    random_state: 42
