# XGBoost Regressor - 고성능 그래디언트 부스팅 회귀기
# 🚀 Gradient Boosting의 혁신, 뛰어난 회귀 성능과 효율성

name: "xgboost_regressor"

model:
  # 직접 동적 import를 통한 XGBoost 회귀기
  class_path: "xgboost.XGBRegressor"
  
  # 하이퍼파라미터 정의 (Optuna 자동 최적화 지원)
  hyperparameters:
    # 🔥 자동 최적화 범위 - XGBoost 특화 하이퍼파라미터
    learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
    n_estimators: {type: "int", low: 100, high: 1000}
    max_depth: {type: "int", low: 3, high: 10}
    subsample: {type: "float", low: 0.6, high: 1.0}
    colsample_bytree: {type: "float", low: 0.6, high: 1.0}
    min_child_weight: {type: "int", low: 1, high: 10}
    gamma: {type: "float", low: 0.0, high: 1.0}
    reg_alpha: {type: "float", low: 0.0, high: 1.0}
    reg_lambda: {type: "float", low: 0.0, high: 1.0}
    
    # 🔧 고정값 - XGBoost 안정성을 위한 필수 설정
    random_state: 42
    objective: "reg:squarederror"
    eval_metric: "rmse"
    verbosity: 0

  # 하이퍼파라미터 튜닝 설정
  hyperparameter_tuning:
    enabled: true
    n_trials: 150  # XGBoost는 더 많은 trial이 유리
    metric: "neg_root_mean_squared_error"
    direction: "maximize"

  # 데이터 로더 정의 (Spine 생성)
  loader:
    name: "regression_loader"
    source_uri: "recipes/sql/loaders/user_features.sql"

  # 피처 증강 정의 (Feature Store 기반)
  augmenter:
    type: "feature_store"
    features:
      # 사용자 기본 정보 피처
      - feature_namespace: "user_demographics"
        features: ["age", "country_code"]
      
      # 사용자 구매 이력 피처  
      - feature_namespace: "user_purchase_summary"
        features: ["ltv", "total_purchase_count", "last_purchase_date"]
      
      # 상품 상세 정보 피처
      - feature_namespace: "product_details"
        features: ["price", "category", "brand"]
      
      # 세션 행동 피처
      - feature_namespace: "session_summary"
        features: ["time_on_page_seconds", "click_count"]

  # 전처리 설정
  preprocessor:
    name: "simple_scaler"
    params:
      criterion_col: null
      # 엔티티 키와 타임스탬프 제외
      exclude_cols: ["user_id", "product_id", "session_id", "event_timestamp"]

  # 데이터 인터페이스 정의
  data_interface:
    task_type: "regression"
    target_col: "target_value"

  # 평가자 설정
  evaluator:
    name: "regression_evaluator"

# 평가 설정
evaluation:
  metrics:
    - "r2_score"
    - "mean_squared_error"
    - "mean_absolute_error"
    - "root_mean_squared_error"
  
  validation:
    method: "train_test_split"
    test_size: 0.2
    random_state: 42

# 💡 사용 예시:
# APP_ENV=dev uv run python main.py train --recipe-file models/regression/xgboost_regressor 