# XGBoost Regressor - Blueprint v17.0 Automated Excellence
# 🚀 Gradient Boosting의 혁신, 회귀에서의 뛰어난 성능과 효율성

# 1. 모델 기본 정보 (직접 동적 import)
class_path: "xgboost.XGBRegressor"

# 2. 데이터 로더 정의
loader:
  name: "regression_dataset"
  source_uri: "bq://recipes/sql/loader/regression_features.sql"
  local_override_uri: "file://local/data/sample_regression.csv"

# 3. 피처 증강기 정의 (🆕 Blueprint v17.0 - Feature Store 방식)
augmenter:
  type: "feature_store"
  features:
    # 기본 수치형 피처
    - feature_namespace: "numerical_features"
      features: ["feature_1", "feature_2", "feature_3", "feature_4"]
    # 사용자 행동 피처
    - feature_namespace: "user_engagement"
      features: ["page_views", "time_spent", "bounce_rate"]
    # 범주형 피처
    - feature_namespace: "categorical_features"
      features: ["category_1", "category_2", "category_3"]
    # 시간 기반 피처
    - feature_namespace: "temporal_features"
      features: ["recency_score", "frequency_score", "monetary_score"]

# 4. 전처리기 정의
preprocessor:
  name: "simple_scaler"
  params:
    criterion_col: null
    exclude_cols: ["user_id", "event_timestamp"]

# 5. 모델 인터페이스
data_interface:
  task_type: "regression"
  
  features:
    feature_1: "numeric"
    feature_2: "numeric"
    feature_3: "numeric"
    feature_4: "numeric"
    page_views: "numeric"
    time_spent: "numeric"
    bounce_rate: "numeric"
    category_1: "category"
    category_2: "category"
    category_3: "category"
    recency_score: "numeric"
    frequency_score: "numeric"
    monetary_score: "numeric"
  
  target_col: "target_value"

# 🆕 6. 하이퍼파라미터 (Dictionary 형식 + 자동 튜닝)
hyperparameters:
  # 🔥 자동 최적화 범위 (XGBoost Regressor 특화)
  learning_rate: {type: "float", low: 0.01, high: 0.3, log: true}
  n_estimators: {type: "int", low: 100, high: 1000}
  max_depth: {type: "int", low: 3, high: 10}
  subsample: {type: "float", low: 0.6, high: 1.0}
  colsample_bytree: {type: "float", low: 0.6, high: 1.0}
  min_child_weight: {type: "int", low: 1, high: 10}
  gamma: {type: "float", low: 0.0, high: 1.0}
  reg_alpha: {type: "float", low: 0.0, high: 1.0}
  reg_lambda: {type: "float", low: 0.0, high: 1.0}
  
  # 🔧 고정값
  random_state: 42
  objective: "reg:squarederror"
  eval_metric: "rmse"

# 🆕 7. 하이퍼파라미터 튜닝 설정
hyperparameter_tuning:
  enabled: true
  n_trials: 100
  metric: "rmse"
  direction: "minimize" 