artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/a359a52679ff47efaf5d5add2109a510/artifacts
end_time: 1753601794094
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: a359a52679ff47efaf5d5add2109a510
run_name: RandomForestClassifier_e2e_classification_test_20250727_163633
source_name: ''
source_type: 4
source_version: ''
start_time: 1753601794044
status: 4
tags: []
user_id: wooshikwon
