class_path: "causalml.inference.meta.TRegressor"
description: "T-Learner (Two Models) for Causal Inference."
library: "causalml"
hyperparameters:
  # 고정 파라미터 (모든 환경 동일)
  fixed:
    random_state: 42
    control_name: "control"
  # Optuna 최적화 대상 파라미터 (범위 지정)
  tunable:
    # Base learner hyperparameters (assuming XGBoost as base)
    n_estimators:
      type: "int"
      range: [10, 300]
      default: 100
    learning_rate:
      type: "float"
      range: [0.01, 0.3]
      default: 0.1
    max_depth:
      type: "int"
      range: [3, 15]
      default: 6
    min_child_weight:
      type: "int"
      range: [1, 10]
      default: 1
    subsample:
      type: "float"
      range: [0.6, 1.0]
      default: 1.0
    colsample_bytree:
      type: "float"
      range: [0.6, 1.0]
      default: 1.0
    gamma:
      type: "float"
      range: [0.0, 5.0]
      default: 0.0
    reg_alpha:
      type: "float"
      range: [0.0, 1.0]
      default: 0.0
    reg_lambda:
      type: "float"
      range: [0.0, 1.0]
      default: 1.0
    # T-Learner specific parameters
    n_bootstraps:
      type: "int"
      range: [50, 500]
      default: 100
    bootstrap_size:
      type: "int"
      range: [1000, 10000]
      default: 5000
    return_ci:
      type: "categorical"
      range: [true, false]
      default: true
    bootstrap_ci:
      type: "categorical"
      range: [true, false]
      default: false
  # 환경별 기본값
  environment_defaults:
    local:
      n_estimators: 50
      learning_rate: 0.1
      max_depth: 4
      n_bootstraps: 50
    dev:
      n_estimators: 100
      learning_rate: 0.05
      max_depth: 6
      n_bootstraps: 100
    prod:
      n_estimators: 200
      learning_rate: 0.03
      max_depth: 8
      n_bootstraps: 200
# 지원 태스크 및 요구사항
supported_tasks: ["causal_inference", "conditional_average_treatment_effect"]
feature_requirements:
  numerical: true
  categorical: true
  text: false