class_path: "causalml.inference.meta.XGBTRegressor"
description: "XGBoost T-Learner for Causal Inference."
library: "causalml"
hyperparameters:
  # 고정 파라미터 (모든 환경 동일)
  fixed:
    random_state: 42
    control_name: "control"
  # Optuna 최적화 대상 파라미터 (범위 지정)
  tunable:
    n_estimators:
      type: "int"
      range: [10, 300]
      default: 100
    learning_rate:
      type: "float"
      range: [0.01, 0.3]
      default: 0.1
    max_depth:
      type: "int"
      range: [3, 15]
      default: 6
    min_child_weight:
      type: "int"
      range: [1, 10]
      default: 1
    subsample:
      type: "float"
      range: [0.6, 1.0]
      default: 1.0
    colsample_bytree:
      type: "float"
      range: [0.6, 1.0]
      default: 1.0
    gamma:
      type: "float"
      range: [0.0, 5.0]
      default: 0.0
    reg_alpha:
      type: "float"
      range: [0.0, 1.0]
      default: 0.0
    reg_lambda:
      type: "float"
      range: [0.0, 1.0]
      default: 1.0
    objective:
      type: "categorical"
      range: ["reg:squarederror", "reg:squaredlogerror"]
      default: "reg:squarederror"
    booster:
      type: "categorical"
      range: ["gbtree", "gblinear", "dart"]
      default: "gbtree"
  # 환경별 기본값
  environment_defaults:
    local:
      n_estimators: 50
      learning_rate: 0.1
      max_depth: 4
      subsample: 0.8
    dev:
      n_estimators: 100
      learning_rate: 0.05
      max_depth: 6
      subsample: 0.9
    prod:
      n_estimators: 200
      learning_rate: 0.03
      max_depth: 8
      subsample: 0.95
# 지원 태스크 및 요구사항
supported_tasks: ["causal_inference", "treatment_effect_estimation"]
feature_requirements:
  numerical: true
  categorical: true
  text: false