artifact_location: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123
creation_time: 1753601669715
experiment_id: '647522906500310123'
last_update_time: 1753601669715
lifecycle_stage: active
name: Local-Experiments
