artifact_uri: /Users/wooshikwon/Desktop/github_wooshikwon/modern-ml-pipeline/mlruns/647522906500310123/ae7c3b8fe0fe482ea0c46298068fc011/artifacts
end_time: 1753603045410
entry_point_name: ''
experiment_id: '647522906500310123'
lifecycle_stage: active
run_id: ae7c3b8fe0fe482ea0c46298068fc011
run_name: RandomForestClassifier_e2e_classification_test_20250727_165724
source_name: ''
source_type: 4
source_version: ''
start_time: 1753603045154
status: 4
tags: []
user_id: wooshikwon
